[package]
name = "observer_ward"
version = "2022.3.13"
authors = ["Kali-Team <root@kali-team.cn>"]
edition = "2021"
description = "Cross platform community web fingerprint identification tool."
license = "MIT"
include = ["LICENSE", "Cargo.toml", "src/**/*.rs"]

[workspace]
members = ["."]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
once_cell = "1.12.0"
clap = { default-features = false, version = "3.2.16", features = ["std"] }
url = { version = "2.1.1", features = ["serde"] }
csv = "1.1.6"
dirs = "4.0.0"
tokio = { version = "1.20.1", default-features = false }
prettytable-rs = "^0.9"
textwrap = "0.15"
log = "0.4.17"
futures = { version = "0.3", features = ["compat"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0"
reqwest = { version = "0.11.10", features = ["socks", "blocking", "gzip"] }
crossterm = "0.24"
observer_ward_what_web = { path = "what_web", package = "what_web" }
observer_ward_what_server = { path = "what_server", package = "what_server" }
zip = "0.6.2"
openssl = { version = "0.10", features = ["vendored"] }
env_logger = "0.9.0"
actix-web-httpauth = "0.8.0"
actix-web = { version = "4.1.0", features = ["openssl"] }
[target.'cfg(not(target_os = "windows"))'.dependencies]
daemonize = "0.4.1"
[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[profile.dev.package."*"]
opt-level = 3
[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
